name: Build Native

on:
  push:
    branches:
      - main

jobs:
  build-native:
    name: Build Native
    runs-on: ubuntu-latest

    steps:
      - name: Pull Repository
        uses: actions/checkout@v4

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: "21"
          cache: "gradle"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Native
        run: gradle build "-Dquarkus.native.enabled=true" "-Dquarkus.package.jar.enabled=false"

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          path: "build/*-runner"
          compression-level: 9